server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_epam
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

logging:
  config: classpath:log-config/log4j2-dev.xml