spring:
  application:
    name: spring-boot-epam
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
          import_files: classpath:import/initial.sql
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  mvc:
    servlet:
      path: /api

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always